import type { NextPage } from "next";
import Head from "next/head";
import Card from "../components/Card";
import Footer from "../components/Footer";

const Home: NextPage = () => {
  return (
    <div className="px-8">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-1 flex-col justify-center items-center py-16 min-h-screen">
        <h1 className="m-0 leading-tight text-6xl text-center hover:no-underline focus:no-underline active:no-underline">
          Welcome to{" "}
          <a href="https://nextjs.org" className="text-[#0070f3] no-underline">
            Next.js!
          </a>
        </h1>

        <p className="my-16 leading-normal text-2xl text-center">
          Get started by editing{" "}
          <code className="bg-[#fafafa] rounded-lg p-3 text-lg font-mono">
            pages/index.tsx
          </code>
        </p>

        <div className="flex items-center justify-center flex-wrap max-w-[800px]  w-full flex-col sm:flex-row">
          <Card
            href="https://nextjs.org/docs"
            title="Documentation"
            description="Learn more about Next.js in the documentation."
          />
          <Card
            href="https://nextjs.org/learn"
            title="Next.js Learn"
            description="Learn about Next.js by following an interactive tutorial!"
          />
          <Card
            href="https://github.com/vercel/next.js/tree/canary/examples"
            title="Examples"
            description="Find other example apps and documentation in the Next.js GitHub repository."
          />
          <Card
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            title="Create Next App"
            description="Was this tool helpful? Let us know how we can improve it!"
          />
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default Home;
